/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedBibliaRouteImport } from './routes/_authenticated/biblia'
import { Route as AuthenticatedContaRouteImport } from './routes/_authenticated/conta'
import { Route as AuthenticatedDevocionaisRouteImport } from './routes/_authenticated/devocionais'
import { Route as AuthenticatedDevocionalDateRouteImport } from './routes/_authenticated/devocional.$date'
import { Route as ApiPublicKiwifyRouteImport } from './routes/api/public/kiwify'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBibliaRoute = AuthenticatedBibliaRouteImport.update({
  id: '/biblia',
  path: '/biblia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContaRoute = AuthenticatedContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDevocionaisRoute =
  AuthenticatedDevocionaisRouteImport.update({
    id: '/devocionais',
    path: '/devocionais',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDevocionalDateRoute =
  AuthenticatedDevocionalDateRouteImport.update({
    id: '/devocional/$date',
    path: '/devocional/$date',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicKiwifyRoute = ApiPublicKiwifyRouteImport.update({
  id: '/api/public/kiwify',
  path: '/api/public/kiwify',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/biblia': typeof AuthenticatedBibliaRoute
  '/conta': typeof AuthenticatedContaRoute
  '/devocionais': typeof AuthenticatedDevocionaisRoute
  '/devocional/$date': typeof AuthenticatedDevocionalDateRoute
  '/api/public/kiwify': typeof ApiPublicKiwifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/biblia': typeof AuthenticatedBibliaRoute
  '/conta': typeof AuthenticatedContaRoute
  '/devocionais': typeof AuthenticatedDevocionaisRoute
  '/devocional/$date': typeof AuthenticatedDevocionalDateRoute
  '/api/public/kiwify': typeof ApiPublicKiwifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/biblia': typeof AuthenticatedBibliaRoute
  '/_authenticated/conta': typeof AuthenticatedContaRoute
  '/_authenticated/devocionais': typeof AuthenticatedDevocionaisRoute
  '/_authenticated/devocional/$date': typeof AuthenticatedDevocionalDateRoute
  '/api/public/kiwify': typeof ApiPublicKiwifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/biblia'
    | '/conta'
    | '/devocionais'
    | '/devocional/$date'
    | '/api/public/kiwify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/biblia'
    | '/conta'
    | '/devocionais'
    | '/devocional/$date'
    | '/api/public/kiwify'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/biblia'
    | '/_authenticated/conta'
    | '/_authenticated/devocionais'
    | '/_authenticated/devocional/$date'
    | '/api/public/kiwify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicKiwifyRoute: typeof ApiPublicKiwifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/biblia': {
      id: '/_authenticated/biblia'
      path: '/biblia'
      fullPath: '/biblia'
      preLoaderRoute: typeof AuthenticatedBibliaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conta': {
      id: '/_authenticated/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof AuthenticatedContaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/devocionais': {
      id: '/_authenticated/devocionais'
      path: '/devocionais'
      fullPath: '/devocionais'
      preLoaderRoute: typeof AuthenticatedDevocionaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/devocional/$date': {
      id: '/_authenticated/devocional/$date'
      path: '/devocional/$date'
      fullPath: '/devocional/$date'
      preLoaderRoute: typeof AuthenticatedDevocionalDateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/kiwify': {
      id: '/api/public/kiwify'
      path: '/api/public/kiwify'
      fullPath: '/api/public/kiwify'
      preLoaderRoute: typeof ApiPublicKiwifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBibliaRoute: typeof AuthenticatedBibliaRoute
  AuthenticatedContaRoute: typeof AuthenticatedContaRoute
  AuthenticatedDevocionaisRoute: typeof AuthenticatedDevocionaisRoute
  AuthenticatedDevocionalDateRoute: typeof AuthenticatedDevocionalDateRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBibliaRoute: AuthenticatedBibliaRoute,
  AuthenticatedContaRoute: AuthenticatedContaRoute,
  AuthenticatedDevocionaisRoute: AuthenticatedDevocionaisRoute,
  AuthenticatedDevocionalDateRoute: AuthenticatedDevocionalDateRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicKiwifyRoute: ApiPublicKiwifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
